name = "flaxia"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "flaxia"
database_id = ""

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "flaxia-content"

[vars]
SANDBOX_ORIGIN = "https://flaxiausercontent.com"
