// Auto-generated by Vite build — do not edit manually
export const SPA_HEAD_TAGS: string = "<link rel=\"stylesheet\" crossorigin href=\"/assets/main-Cz1w9Mp9.css\">\n  <link rel=\"modulepreload\" crossorigin href=\"/assets/main-CKhJ-iQo.js\">\n  <script type=\"module\" crossorigin src=\"/assets/main-CKhJ-iQo.js\"></script>";
