// Auto-generated by Vite build — do not edit manually
export const SPA_HEAD_TAGS: string = "<link rel=\"stylesheet\" crossorigin href=\"/assets/main-C28Nh092.css\">\n  <link rel=\"modulepreload\" crossorigin href=\"/assets/main-DGINDint.js\">\n  <script type=\"module\" crossorigin src=\"/assets/main-DGINDint.js\"></script>";
