// Auto-generated by Vite build — do not edit manually
export const SPA_HEAD_TAGS: string = "<link rel=\"stylesheet\" crossorigin href=\"/assets/main-Ce28e3cc.css\">\n  <link rel=\"modulepreload\" crossorigin href=\"/assets/main-COn8UlwE.js\">\n  <script type=\"module\" crossorigin src=\"/assets/main-COn8UlwE.js\"></script>";
